@startuml
'https://plantuml.com/class-diagram

class Context

abstract class AbstractExpression {
    {abstract} interpret(Context c)
}

AbstractExpression <|-- Expression
AbstractExpression <|-- NonterminalExpression


class Expression {
    interpret()
}

class NonterminalExpression {
    interpret()
}
@enduml