@startuml
'https://plantuml.com/class-diagram

class Originator {
    state
    Memento create_memento()
    set_memento(Memento memento)
}

class Memento {
    state
}

class Caretaker {
    Memento memento
}

Originator .. Memento
Caretaker .. Memento


@enduml