@startuml
'https://plantuml.com/class-diagram

abstract class Strategy {
    {abstract} unique(s: str)
}

class SetUniqueStragety {
    unique(s: str)
}

class SortPairUniqueStrategy {
    unique(s: str)
}

Strategy <|-- SetUniqueStragety
Strategy <|-- SortPairUniqueStrategy


@enduml